name: CI

on:
  pull_request:
    branches:
      - master

concurrency:
  group: ci-it-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  check-license:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source codes
        uses: actions/checkout@v2

      - name: Check License
        uses: apache/skywalking-eyes@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source codes
        uses: actions/checkout@v2

      - name: Run unit tests
        run: docker run --rm -v $(pwd):/app --entrypoint pytest ghcr.io/fgksgf/deeprelease-base:0.1.0 pytest
