name: Test

on:
  pull_request:
    branches:
      - master

concurrency:
  group: test-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test-gha:
    runs-on: ubuntu-latest
    steps:
      - name: Generate the release notes
        uses: fgksgf/DeepRelease@master
        with:
          repo: 'apache/skywalking-python'
          debug: 'True'

      - name: Check the file
        run: cat release-notes.md

